# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 971cbb12781f6e2e0ff9f72e4fabdc63b9fc2e113de0de50a4d443758d68fc4fe271016f0c32ea250e3c8588615b6d8be179b3b742237f633144a9198d9f19cf

test:
  secret_key_base: e266f2adc7a5cfc59f4a017332b3751019e4d8e599adc03d47b5e9fff6f3e57c9cb95778f15fa9f77bfa93588186d9251a66f65aaa1b635c0a1815677be296c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
